### PR TITLE
hotfix - Fix function name

### PR DESCRIPTION
**Pull request by jmaumene**
Error in function name. 
Fatal error Class 'hipay_professionalcheckModuleFrontController' not found.
Only one 'n' to professional

### CODE REVIEW

**Comment by jprotin** [comment]
Hi Julien,

Can you change your pull request to hipay:develop and not in hipay:master ?

Thank you for your contribution, we will test and release quickly ! !

**Comment by jmaumene** [comment]
Ok

**Comment by jprotin** [comment]
Thank you, we init a new release !

**Comment by jprotin** [comment]
Julien,

https://github.com/hipay/hipay-professional-sdk-prestashop/releases/tag/1.0.3 

New release here ! Thx a lot !

**Pull request merged**
